# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    setup_ci(force: true) if is_ci

    match(
      type: "appstore",
      app_identifier: "com.MatchTest.Release",
      keychain_name: "fastlane_tmp_keychain",
      keychain_password: "",
      readonly: true
    )

    if is_ci
      keychain_path = "~/Library/Keychains/fastlane_tmp_keychain-db"
      sh("security unlock-keychain -p '' #{keychain_path}")
      sh("security set-key-partition-list -S apple-tool:,apple: -s -k '' #{keychain_path}")
    end

    api_key = app_store_connect_api_key(
      key_id: ENV["key_id"],
      issuer_id: ENV["issuer_id"],
      key_content: ENV["key"],
      is_key_content_base64: true
    )
 
    build_app(
      workspace: "MatchTest.xcworkspace",
      scheme: "MatchTest-Release",
      configuration: "Beta",
      export_method: "app-store",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      username: ENV["APPLE_ID"],
      app_identifier: "com.MatchTest.Release",
      skip_waiting_for_build_processing: true,
      uses_non_exempt_encryption: false
    )
  end
end
